### ISSUE TITLE
Issues during installation and with module shap

### ISSUE THREAD

**Issue by AndreasTraut** [mljar/mljar-supervised#124]
I tried to install but already get an error during the installation process: 
![installation](https://user-images.githubusercontent.com/55921277/87794344-c2d18b80-c846-11ea-8efc-dc1758f3df42.jpg)
I didn't see, that Visual Studio is a requirement for "Mljar-Supervised". After having downloaded "Visual Studio" I tried to use your example "binary_classifier.py" but it says, that the "module shap is missing" even if it is there in the correct folder: 
![shap_missing](https://user-images.githubusercontent.com/55921277/87794635-31aee480-c847-11ea-9bde-483aec344834.jpg)
And when I have a look into "shap.py" I see another "import shap" there (I don't know if this causes the error): 
![line13](https://user-images.githubusercontent.com/55921277/87794296-b2211580-c846-11ea-8e88-ebb55f7c8bb7.jpg)

**Comment by pplonski** [comment]
@AndreasTraut thank you for reporting the issue. There is no need for Visual Studio in `mljar-supervised`. From what I see, you have an installation problem while installing the `shap` package. The message is that you need a Microsoft Visual C++ compiler which can be installed with Visual Studio IDE. Can you give me more details about what version of the operating system are you using, I will try to reproduce this bug.

By the way, `mljar-supervised` should work with Spyder IDE as well. Personally, I'm using Visual Studio Code because it has nice preview of markdown reports. I believe that Spyder should preview markdown reports as well.

Thank you! :+1:

**Comment by AndreasTraut** [comment]
I am using a Windows 10 Pro systen, x64, Intel i7-8799 CPU, 3.2 GHz, 16GB RAM. 
Spyder/Juypter from Anaconda Distribution, GitHub Desktop (newest versions each). 

Let me know what else you need to solve my problem. Thanks for your help!
