### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by ijeffking** [mljar/mljar-supervised#182]
While training the model on the dataset 'Predict The Flight Ticket Price Hackathon' I encountered the abovementioned error

```py
# train models with AutoML
automl = AutoML(mode="Compete")
automl.fit(X_train, y_train)
```

Link to data https://www.machinehack.com/hackathons/predict_the_flight_ticket_price_hackathon

**Comment by pplonski** [comment]
Thank you @ijeffking for reporting!

**Comment by pplonski** [comment]
I couldn't reproduce this issue with provided dataset:

```py
import numpy as np
import pandas as pd
from supervised import AutoML

df = pd.read_csv("~/Downloads/Flight_Datasets/Data_Train.csv")

X = df[df.columns[:-1]]
y = df[df.columns[-1]]

automl = AutoML(mode="Compete")
automl.fit(X, y
```

That's why I added an option to log all errors to `errors.md` report. The user will get information about the error displayed in the terminal and all error details will be saved to the report file. The training will not be stopped in the case of one model will fail.

**Comment by pplonski** [comment]
After 1 hour of training on data from hackathon (and no manual preprocessing) I got a 55-th place out of 494 participants. Public score: `0.94711` :sunglasses:

**Comment by ijeffking** [comment]
Excellent Piotr
That’s a great score. Way to go!!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
