### ISSUE TITLE
 Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#265]
The warning message:

```
Setting a random_state has no effect since shuffle is False. 
This will raise an error in 0.24. 
You should leave random_state to its default (None), or set shuffle=True.
```

**Comment by dkinneyBU** [comment]
This is still happening in version 2.2.3, with just a simple setup statement: clf1 = setup(df, target = 'diagnosis') Please advise.

**Comment by tracyisme** [comment]
how to write the code?thankyou

**Comment by tracyisme** [comment]
following codes has this error,how to modify it, thank you

scoring = 'accuracy'  
models = []  
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr'))) 
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('QDA', QuadraticDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
models.append(('RFC', RandomForestClassifier(n_estimators=10)))
models.append(('ADA', AdaBoostClassifier(n_estimators=100)))
models.append(('MLPC', MLPClassifier(solver='lbfgs', alpha=1e5,hidden_layer_sizes=(5, 5), random_state=1)))
results=[]
names=[]
for name, model in models:
        kfold=model_selection.KFold(n_splits=10,random_state=seed)
        cv_results=model_selection.cross_val_score(model,X_train,Y_train,cv=kfold,scoring="accuracy")
        results.append(cv_results)
        names.append(name)
        mpdels.set.shuffle=True
        msg="%s:%f" % (name,cv_results.mean())
print(msg)

**Comment by Besideme** [comment]
https://www.allinfohere.net/2021/05/Scikit-learn-Cross-Validation-Setting-a-randomstate-has-no-effect-since-shuffle-is-False.html
ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
To fix this ValueError you have to write shuffle=True

from sklearn.model_selection import StratifiedKFold

skfolds=StratifiedKFold(n_splits=3, shuffle=True,  random_state=42)

**Comment by tracyisme** [comment]
Dear,
Thank you very much. I have found the problem and solve it. It's very helpful.
Tracy


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mljar/mljar-supervised"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mljar/mljar-supervised]  Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True. (#265)





 
https://www.allinfohere.net/2021/05/Scikit-learn-Cross-Validation-Setting-a-randomstate-has-no-effect-since-shuffle-is-False.html
 ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
 To fix this ValueError you have to write shuffle=True
 
from sklearn.model_selection import StratifiedKFold
 
skfolds=StratifiedKFold(n_splits=3, shuffle=True,  random_state=42)
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peeyushkumarofficial** [comment]
@tracyisme can you please tell me how it worked? I used the solution from the link 

https://www.allinfohere.net/2021/05/Scikit-learn-Cross-Validation-Setting-a-randomstate-has-no-effect-since-shuffle-is-False.html

still getting the error, while compare_models()
