### ISSUE TITLE
How can I reproduce the figures showed in report

### ISSUE THREAD

**Issue by xuzhang5788** [mljar/mljar-supervised#385]
In the report, there are several figures. If I want to modify the figures, what should I do?

**Comment by pplonski** [comment]
@xuzhang5788 this should be possible. You can load out-of-folds predictions and reproduce the plots. Out-of-folds predictions are saved in each model directory. Which plot would you like to reproduce?

There is an example notebook where I do plots manually (but on test data rather than train data and out-of-folds predictions) https://deepnote.com/project/Telco-Customer-Churn-AutoML-classification-tVxEwqLNQ3SL0RcGJ5WsdA/%2Fnotebook.ipynb
