### ISSUE TITLE
please add model correlation heatmap

### ISSUE THREAD

**Issue by aplonska** [mljar/mljar-supervised#386]

**Comment by pplonski** [comment]
Spearman correlation is computed between all trained models at the end of AutoML training. The example below:

![image](https://user-images.githubusercontent.com/6959032/116699773-49b2b780-a9c6-11eb-8dfc-e2a8d13551ce.png)

For classification the correlation is computed based on proba values. For multiclass the average of correlation for each class is done.

**Comment by pplonski** [comment]
Please resize in the case of many models.

**Comment by pplonski** [comment]
I added larger figure in the case of the many models:

![image](https://user-images.githubusercontent.com/6959032/116999372-d075d600-acdf-11eb-8ccb-15737e166e1b.png)

**Comment by Tonywhitemin** [comment]
Hi pplonski,
Good day! I am now study this heatmap but have some questions on it...
Could you please help?
If follow the above commend you said:
**"For classification the correlation is computed based on proba values. For multiclass the average of correlation for each class is done."**
Since this heatmap is bases on different models, may I know it used what parameters or value to do the correlation?
Could you tell me what is the mechanism of it?
Thanks!

**Comment by pplonski** [comment]
The correlation is computed between each model's predictions and target.  It is computed with `scipy.stats.spearmanr`.
