### ISSUE TITLE
mljar website is down

### ISSUE THREAD

**Issue by Fanshia** [mljar/mljar-supervised#399]
Can't login: https://cloud.mljar.com/accounts/signin/
Have been seen this for more than a week

**Comment by pplonski** [comment]
@Fanshia thank you for reporting!

The problem is fixed. Should work now.

We are working now on new MLJAR product - it will be notebook alike app for building ML models. It will use `mljar-supervised` package for AutoML, it will have graphical interface to setup AutoML training details. It will be desktop based. 

Some very first screenshot
![image](https://user-images.githubusercontent.com/6959032/119239124-55b61300-bb47-11eb-852b-ac353764837f.png)

@Fanshia would you be interested in testing it? What operating system are you using?
