### ISSUE TITLE
Unbalanced binary classification dataset

### ISSUE THREAD

**Issue by tijeco** [mljar/mljar-supervised#413]
If I have a dataset that has 10 times more samples for one class than another, does mljar do anything to account for this, or should I be balancing the dataset beforehand?

**Comment by pplonski** [comment]
@tijeco mljar will handle the imbalanced data in the case of a very high imbalance (less than 20 samples of the class) otherwise it doesn't change the class distribution. 

The 1:10 ratio is not a very high imbalance, you can try to learn models without any changes in the distribution. You can also do some balancing on your data and then train AutoML on new data. You can compare the final result (imbalanced vs balanced) on hold-out data.

**Comment by tijeco** [comment]
@pplonski Thanks for the response! I figured mljar may have some sort of built in way of dealing with this, but I just wanted to verify with you!
