### ISSUE TITLE
How many tree are in my Random Forest?

### ISSUE THREAD

**Issue by elcolie** [mljar/mljar-supervised#416]
In the summary page. I see the report on each classifier. One that I am pay attention most is `RandomForest`
```
Random Forest
n_jobs: -1
criterion: gini
max_features: 0.5
min_samples_split: 20
max_depth: 4
eval_metric_name: logloss
num_class: 13
explain_level: 0
```
My questions
1. Does `mljar` find the optimal `trees` and `max_depth`?
2. How can I see the number of `trees` in the report?

**Comment by pplonski** [comment]
Hey @elcolie! Great question. The `max_depth` is the hyperparameter that is set before training. In your example, it is set to `4`. The number of trees is optimized with early stopping. Its value is pointed in the learning curve plot with a vertical line (search for Learning curves in the README.md file).

**Comment by elcolie** [comment]
> Hey @elcolie! Great question. The `max_depth` is the hyperparameter that is set before training. In your example, it is set to `4`. The search for optimal `max_depth` is done by checking different models for RF. If you have other Random Forest models they might have different `max_depth` values.

I have only single `RandomForest(RF)`, but 3 `DecisionTree`. 
Does it mean this `RF` is optimal at `max_depth=4`?

> The number of trees is optimized with early stopping. Its value is pointed in the learning curve plot with a vertical line (search for Learning curves in the README.md file).

How to get the exact tree number there?

![image](https://user-images.githubusercontent.com/18206728/123110140-045eb380-d466-11eb-88de-543d67189d90.png)

**Comment by pplonski** [comment]
If you have one model of Random Forest then you can't say that `max_depth=4` is optimal (or close to optimal). You need to check much more models with Random Forest or you can try Optuna mode to tune Random Forest parameters.

You used 10-fold cross validation, so you have different number of trees for each learner (for each cross validation step). If you want I can add a print out in the README.md file with optimal tree number for each learner. Because right now it is hard to read from the plot (my fault).

Why do you need to know the optimal tree number in RF?

Is your dataset very small or is it very noisy?

**Comment by elcolie** [comment]
> Why do you need to know the optimal tree number in RF?

I need best hyper parameter in my production system



> Is your dataset very small or is it very noisy?

It is small

**Comment by pplonski** [comment]
@elcolie please run Optuna mode with following code:

```python
automl = AutoML(mode="Optuna", optuna_time_budget=600, algorithms=["Random Forest"])
automl.fit(X, y)
```

You will get one model wtih Random Forest but it will be trained after extensive hyperparameters search with Optuna framework. You can check details of tuning in `optuna/README.md` file.

I set `optuna_time_budget=600` because your dataset is small and 10 minutes should be enough to check more than 50 models (you will see in terminal output how many trials were run).

Please let me know if final model with Optuna is better than first RF.
