### ISSUE TITLE
1.0.0. Scikit-learn warnings

### ISSUE THREAD

**Issue by aplonska** [mljar/mljar-supervised#466]
Please upgrade to the newest version of Scikit-learn 1.0.0.

**Comment by pplonski** [comment]
In the `requirements.txt` we have `scikit-learn>=0.24.2` and looks like the newest version of `scikit-learn` is installed currently (when fresh conda install is performed).

Because of this we have a bunch of new warnings from sklearn:
- Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
- The attribute `n_features_` is deprecated in 1.0 and will be removed in 1.2. Use `n_features_in_` instead.
- X does not have valid feature names, but MLPClassifier was fitted with feature names

I will try to fix them

**Comment by pplonski** [comment]
I hide/fix warnings
