### ISSUE TITLE
Confuse about why we need hill_climbing step step

### ISSUE THREAD

**Issue by bladesaber** [mljar/mljar-supervised#506]
Hello,  I am confuse about why the hill climbing step can improve the performance of model. It seems that the optuna will try to find the best config param of the model automatically,  so why we need to adjust hyperparameter by ourselves. I also check the hill climb function, I find the key updated by hill climbing step is also optimized by optuna in Object function(such as RandomForestObjective). 

Looking forward to some tips and insight. Thanks everyone. ^_^

**Comment by pplonski** [comment]
Hi @bladesaber, 

You are right. It is very low chance that the hill-climbing step will improve a model after Optuna optimization. If I remeber correctly, the hill-climbing step is disabled by default in Optuna mode (because of this).

But if you enable the hill-climbing step after Optuna optimization, it is a chance that two models (from Optuna and hill-climbing) can be combined together in the ensemble. And together will give good performance.

It all depends on your data.

**Comment by bladesaber** [comment]
Thanks for explanation.
