### ISSUE TITLE
Requierements issue

### ISSUE THREAD

**Issue by DanielR59** [mljar/mljar-supervised#522]
In the installation  for development is required python3.6. However, when installing requirements.txt [Pandas 1.2.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html#increased-minimum-version-for-python) has no longer support for python 3.6. 
Also there's issue with scipy 1.6.1. Last support for python3.6 is 1.5.4

**Comment by pplonski** [comment]
@DanielR59 thanks for reporting! 

@MaciekEO could you please look at it, thanks.

**Comment by MaciekEO** [comment]
Hey @DanielR59. I just checked it and you are right. Pandas 1.2.0 release supports Python 3.7.1 or higher and as for Scipy since version 1.6.0, it supports Python 3.7 or higher. Below you have the documentation for these libraries.
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html#increased-minimum-version-for-python
https://scipy.github.io/devdocs/release.1.6.0.html#issues-closed-for-1-6-0

**Comment by pplonski** [comment]
Thank you @MaciekEO and @DanielR59!
