### ISSUE TITLE
Slow Inference Time of Compete Model in MLJAR

### ISSUE THREAD

**Issue by HanChangHun** [mljar/mljar-supervised#658]
Hello,

I've been using MLJAR for training my data and have noticed longer inference times with my trained models. It seems that the slowdown might be related to ensembles or stacked ensembles, but I'm not entirely sure. I'm looking for ways to improve the inference speed without significantly compromising accuracy.

Is there a recommended approach or any specific settings in MLJAR that I can tweak to achieve faster inference times while maintaining a reasonable level of accuracy?

Thank you!

**Comment by pplonski** [comment]
Hi @HanChangHun,

That's great question. The inference time for `Compete` mode can be very large because it usually consists of many models.

There is a `Perform` mode, that maximize accuracy and keep prediction time below the threshold.To set prediction time threshold please set `max_single_prediction_time`. You can read more in the docs https://supervised.mljar.com/api/

**Comment by HanChangHun** [comment]
@pplonski 

Thank you for your prompt and helpful response!
